services:
  rekku_freedom_project:
    build: .
    container_name: rekku_freedom_project
    hostname: luna-workstation
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
      - "${VNC_PORT:-6901}:6901"
    volumes:
      - ./persona/home:/home/rekku
      - ./persona/mind:/app/persona
      - ./persona/webtop_config:/config
      - ./logs:/config/logs
      - .env:/app/.env:ro
    environment:
      - WEBVIEW_PORT=${WEBVIEW_PORT:-5006}
      - WEBVIEW_HOST=${WEBVIEW_HOST:-localhost}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-720}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      - TZ=${TZ:-Asia/Tokyo}
      - CUSTOM_USER=${CUSTOM_USER:-rekku}
      - HOME=${REKKU_HOME:-/home/rekku}
      - PASSWORD=${PASSWORD:-"password"}
      - SECURE_CONNECTION=0
    restart: unless-stopped
    stdin_open: true
    tty: true
