services:
  rekku_freedom_project:
    image: rekku_freedom_project:latest
    container_name: rekku_freedom_project
    hostname: luna-workstation
    user: "1000:1000"
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
      - "5002:5006"
    volumes:
      - ./persona:/app/persona
      - ./rekku_home:/home/rekku
      - .env:/app/.env:ro
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=rekku
      - PASSWORD=${REKKU_PASSWORD}
      - SECURE_CONNECTION=0
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true


