services:
  rekku_freedom_project:
    image: xargonwan/rekku_freedom_project:${IMAGE_VERSION:-latest}
    container_name: rekku_freedom_project
    hostname: luna-workstation
    env_file:
      - .env
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
      - "${VNC_PORT:-6901}:6901"
    volumes:
      - ./persona/home:/home/rekku
      - ./persona/mind:/app/persona
      - ./persona/webtop_config:/config
      - ./logs:/config/logs
      - .env:/app/.env:ro
    environment:
      - WEBVIEW_PORT=${WEBVIEW_PORT:-5006}
      - WEBVIEW_HOST=${WEBVIEW_HOST:-localhost}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-720}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      - TZ=${TZ:-Asia/Tokyo}
      - CUSTOM_USER=${CUSTOM_USER:-rekku}
      - HOME=${REKKU_HOME:-/home/rekku}
      - PASSWORD=${PASSWORD:-"password"}
      - SECURE_CONNECTION=0
      - VNC_PASSWORD=${PASSWORD:-"password"}
      - DB_HOST=${DB_HOST:-rfp-db}
    restart: unless-stopped
    stdin_open: true
    tty: true

  rfp-db:
    container_name: rfp-db
    image: mariadb:11
    env_file:
      - .env
    ports:
      - "${EXT_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-rekku}
      MYSQL_USER: ${DB_USER:-rekku}
      MYSQL_PASSWORD: ${DB_PASS:-rekku}
    command: --bind-address=0.0.0.0
    volumes:
      - rfp_db_data:/var/lib/mysql

  rfp-db-backup:
    container_name: rfp-db-backup
    image: tiredofit/db-backup
    platform: ${PLATFORM_BACKUP:-linux/amd64}
    env_file:
      - .env
    depends_on:
      - rfp-db
    environment:
      DB_TYPE: mysql
      DB_HOST: ${DB_HOST:-rfp-db}
      DB_NAME: ${DB_NAME:-rekku}
      DB_USER: ${DB_USER:-rekku}
      DB_PASS: ${DB_PASS:-rekku}
      DB_DUMP_FREQ: 60
      DB_CLEANUP_TIME: 1440
      CONTAINER_TIMEZONE: Asia/Tokyo
      COMPRESSION: GZ
      DB_DUMP_TARGET: /backup
    volumes:
      - ./backups:/backup
    restart: unless-stopped

volumes:
  rfp_db_data:
