services:

  rfp:
    image: xargonwan/rekku_freedom_project:${IMAGE_VERSION:-latest}
    container_name: rfp
    hostname: luna-workstation
    env_file:
      - .env
    ports:
      - "${WEBVIEW_HTTPS_PORT:-3000}:3000"
      - "${WEBVIEW_HTTP_PORT:-3001}:3001"
      - "${CLI_SERVER_PORT:-5555}:5555"
      - "${WEBUI_PORT:-8000}:${WEBUI_PORT:-8000}"
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - rfp_data:/config
      - ./logs:/app/logs
      - ./avatars:/app/res/synth_webui/avatars
      - .env:/app/.env:ro
    environment:
      - WEBVIEW_PORT=${WEBVIEW_PORT:-5006}
      - WEBVIEW_HOST=${WEBVIEW_HOST:-localhost}
      - WEBUI_PORT=${WEBUI_PORT:-8000}
      - WEBUI_HOST=${WEBUI_HOST:-0.0.0.0}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-720}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      - TZ=${TZ:-Asia/Tokyo}
      - SECURE_CONNECTION=${SECURE_CONNECTION:-1}
      - DB_HOST=${DB_HOST:-rfp-db}
      - CLI_SERVER_PORT=${CLI_SERVER_PORT:-5555}
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - rfp-db
    networks:
      - rfp_network

  rfp-db:
    container_name: rfp-db
    hostname: rfp-db
    image: mariadb:11
    env_file:
      - .env
    ports:
      - "${EXT_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-rekku}
      MYSQL_USER: ${DB_USER:-rekku}
      MYSQL_PASSWORD: ${DB_PASS:-rekku}
    command: --bind-address=0.0.0.0
    volumes:
      - rfp_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - rfp_network

  rfp-db-backup:
    container_name: rfp-db-backup
    image: tiredofit/db-backup
    platform: ${PLATFORM_BACKUP:-linux/amd64}
    env_file:
      - .env
    depends_on:
      - rfp-db
    environment:
      DB_TYPE: mysql
      DB_HOST: ${DB_HOST:-rfp-db}
      DB_NAME: ${DB_NAME:-rekku}
      DB_USER: ${DB_USER:-rekku}
      DB_PASS: ${DB_PASS:-rekku}
      DB_DUMP_FREQ: 60
      DB_CLEANUP_TIME: 1440
      CONTAINER_TIMEZONE: Asia/Tokyo
      COMPRESSION: GZ
      DB_DUMP_TARGET: /backup
    volumes:
      - ./backups:/backup
    restart: unless-stopped
    networks:
      - rfp_network

volumes:
  rfp_db_data:
  rfp_data:

networks:
  rfp_network:
    driver: bridge
    name: rfp_network
