services:
  rekku_freedom_project:
    build: .
    container_name: rekku_freedom_project
    hostname: luna-workstation
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
      - "6901:6901"
    volumes:
      - ./persona/home:/home/rekku
      - ./persona/mind:/app/persona
      - ./persona/webtop_config:/config
      - ./logs:/config/logs
      - .env:/app/.env:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - CUSTOM_USER=${CUSTOM_USER:-abc}
      - PASSWORD=${PASSWORD}
      - SECURE_CONNECTION=0
    restart: unless-stopped
    stdin_open: true
    tty: true
