services:
  rekku_the_bot:
    container_name: rekku_the_bot
    image: rekku_the_bot:latest
    restart: on-failure
    environment:
      - TELEGRAM_TOKEN=${REKKU_TELEGRAM_TOKEN}
      - OWNER_ID=${TELEGRAM_OWNER_ID}
      - WEBVIEW_PORT=${REKKU_WEBVIEW_PORT:-5005}
      - WEBVIEW_HOST=${REKKU_WEBVIEW_HOST:-localhost}
    ports:
      - "${REKKU_WEBVIEW_PORT:-5005}:${REKKU_WEBVIEW_PORT:-5005}"
    volumes:
      - ./logs:/app/debug_logs
      - ./rekku_home:/home/rekku
    env_file:
      - .env
