services:

  synth:
    image: xargonwan/synthetic_heart:${IMAGE_VERSION:-latest}
    container_name: synth
    hostname: synthetic-heart
    env_file:
      - .env
    ports:
      - "${SELKIES_HTTPS_PORT:-3000}:3000"
      - "${SELKIES_HTTP_PORT:-3001}:3001"
      - "${CLI_SERVER_PORT:-5555}:5555"
      - "${WEBUI_PORT:-8000}:${WEBUI_PORT:-8000}"
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - synth_data:/config
      - synth_res:/app/res
      - ./logs:/app/logs
      - .env:/app/.env:ro
    environment:
      - WEBVIEW_PORT=${WEBVIEW_PORT:-5006}
      - WEBVIEW_HOST=${WEBVIEW_HOST:-localhost}
      - WEBUI_PORT=${WEBUI_PORT:-8000}
      - WEBUI_HOST=${WEBUI_HOST:-0.0.0.0}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-720}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      - TZ=${TZ:-Asia/Tokyo}
      - SECURE_CONNECTION=${SECURE_CONNECTION:-1}
      - DB_HOST=${DB_HOST:-synth-db}
      - CLI_SERVER_PORT=${CLI_SERVER_PORT:-5555}
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - synth-db
    networks:
      - synth_network

  synth-db:
    container_name: synth-db
    hostname: synth-db
    image: mariadb:11
    env_file:
      - .env
    ports:
      - "${EXT_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-synth}
      MYSQL_USER: ${DB_USER:-synth}
      MYSQL_PASSWORD: ${DB_PASS:-synth}
    command: --bind-address=0.0.0.0
    volumes:
      - synth_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - synth_network

volumes:
  synth_db_data:
  synth_data:
  synth_res:

networks:
  synth_network:
    driver: bridge
    name: synth_network


