services:
  rekku_freedom_project:
    build:
      context: .
      args:
        - GITVERSION_TAG=${GITVERSION_TAG:-dev}
    image: rekku_freedom_project:latest
    container_name: rekku_freedom_project
    hostname: luna-workstation
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
      - "5007:6901"
    volumes:
      - ./persona/mind:/app/persona
      - ./persona/home:/home/abc
      - ./persona/webtop_config:/config
      - ./logs:/config/logs
      - .env:/app/.env:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PASSWORD}
      - SECURE_CONNECTION=0
    restart: unless-stopped
    stdin_open: true
    tty: true
