services:
  rekku_freedom_project:
    build: .
    image: rekku_freedom_project:latest
    container_name: rekku_freedom_project
    hostname: luna-workstation
    ports:
      - "${WEBVIEW_PORT:-5006}:3000"
    volumes:
      - ./persona:/app/persona
      - ./rekku_home:/home/rekku
      - .env:/app/.env:ro
    # Albeit these variables are in the env file
    # they must be defined here for Docker to use them
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PASSWORD=${PASSWORD:-rekku}
      - SECURE_CONNECTION=0
      - HOME=${HOME:-/home/rekku}
    restart: unless-stopped
    stdin_open: true
    tty: true


