services:
  rekku_freedom_project:
    container_name: rekku_freedom_project
    hostname: luna-workstation
    image: rekku_freedom_project:latest
    user: "1000:1000"
    volumes:
      - persona:/app/persona:rw
      - ./rekku_home:/home/rekku:rw
      - .env:/app/.env:ro
    ports:
      - 5001:3000   # Webtop access (HTTPS)
      - 5002:5006   # Webview del bot
    restart: on-failure
    env_file:
      - .env
