#!/command/with-contenv bash
set -e

# Ensure Rekku config directory exists and is writable
mkdir -p /config/.config/
sudo chmod a+rwx -R /config

echo "[S6 Rekku] Attendo /tmp/.X11-unix/X1..."
while [ ! -e /tmp/.X11-unix/X1 ]; do
    sleep 2
    echo "[S6 Rekku] Still waiting for /tmp/.X11-unix/X1..."
done

echo "[S6 Rekku] Avvio Rekku Freedom Project..."
cd /app
exec /app/rekku.sh run
