version: '3.8'
services:
  rekku_desktop:
    build:
      context: .
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    container_name: rekku_desktop
    ports:
      - "5006:5005"
    volumes:
      - ./rekku_home:/home/rekku
    env_file:
      - ../.env
    environment:
      WEBVIEW_HOST: ${WEBVIEW_HOST}
      WEBVIEW_PORT: ${WEBVIEW_PORT:-5005}
    restart: always
