#!/command/with-contenv bash
set -e

ABC_USER=abc
ABC_UID=$(id -u "$ABC_USER")
ABC_GID=$(id -g "$ABC_USER")

mkdir -p /config/.config/chromium-rfp || true

# Ensure /config is owned by abc and has user rwx permissions
chown -R "$ABC_UID:$ABC_GID" /config || true
chmod -R u+rwX /config || true

echo "[S6 Rekku] Ownership and permissions of /config set to abc."
