name: "Rekku Freedom Project - Release"

on:
  push:
    branches:
      - "main"
      - "develop"
      - "fix/**"
      - "feat/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "fix/**"
      - "feat/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: '5.x'

    - name: Determine version with GitVersion
      id: gitversion_build
      uses: gittools/actions/gitversion/execute@v0.9.14
      with:
        useConfigFile: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image (amd64)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        build-args: TARGETARCH=amd64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}

    - name: Build and push Docker image (arm64)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64
        build-args: TARGETARCH=arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-arm

    - name: Tag image as latest (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }} ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest

    - name: Tag arm image as latest-arm (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-arm ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-arm
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-arm

    - name: Tag image as latest-develop (develop branch only)
      if: github.ref == 'refs/heads/develop'
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }} ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-develop
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-develop

    - name: Tag arm image as latest-develop-arm (develop branch only)
      if: github.ref == 'refs/heads/develop'
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-arm ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-develop-arm
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:latest-develop-arm

    - name: Tag image for non-main and non-develop branches
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
      run: |
        branch_name=${GITHUB_REF#refs/heads/}
        branch_name=${branch_name#refs/pull/}
        sanitized_branch_name=$(echo "$branch_name" | sed 's|/|-|g')
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }} ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-$sanitized_branch_name
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-$sanitized_branch_name

    - name: Tag arm image for non-main and non-develop branches
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
      run: |
        branch_name=${GITHUB_REF#refs/heads/}
        branch_name=${branch_name#refs/pull/}
        sanitized_branch_name=$(echo "$branch_name" | sed 's|/|-|g')
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-arm ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-$sanitized_branch_name-arm
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rekku_freedom_project:${{ steps.gitversion_build.outputs.semVer }}-$sanitized_branch_name-arm

  cleanup-images:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Remove dangling and old PR images from Docker Hub
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          repo="$USERNAME/rekku_freedom_project"
          token=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)

          # Delete untagged images
          curl -s -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/$repo/images?page_size=100" | \
            jq -r '.results[] | select((.digest != null) and (.tags | length == 0)) | .digest' | while read digest; do
              echo "Deleting dangling image $digest"
              curl -s -H "Authorization: JWT $token" -X DELETE "https://hub.docker.com/v2/repositories/$repo/images/$digest/"
            done

          # Delete PR tags older than two weeks
          cutoff=$(date -u -d '14 days ago' +%s)
          curl -s -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/$repo/tags?page_size=100" | \
            jq -r '.results[] | .name + " " + .last_updated' | while read name updated; do
              if [[ "$name" == *-pr-* ]]; then
                ts=$(date -u -d "$updated" +%s)
                if [ $ts -lt $cutoff ]; then
                  echo "Deleting tag $name (older than two weeks)"
                  curl -s -H "Authorization: JWT $token" -X DELETE "https://hub.docker.com/v2/repositories/$repo/tags/$name/"
                fi
              fi
            done

