name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up image tag
      id: vars
      run: echo "tag=rekku_the_bot:${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.vars.outputs.tag }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Tag image for GitHub Container Registry
      run: |
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker tag ${{ steps.vars.outputs.tag }} ghcr.io/$REPO_OWNER_LC/rekku_the_bot:latest
    - name: Push image to GitHub Container Registry
      run: |
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_OWNER_LC/rekku_the_bot:latest
    - name: Make image public (optional, requires gh CLI)
      run: |
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        gh api --method PATCH /user/packages/container/rekku_the_bot/versions/latest \
          -H "Accept: application/vnd.github+json" \
          -F visibility=public
      env:
        GH_TOKEN: ${{ secrets.CR_PAT }}
