name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rekku_the_bot:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag image for GitHub Container Registry
      run: |
        IMAGE_TAG=rekku_the_bot:$(date +%s)
        docker tag $IMAGE_TAG ghcr.io/${{ github.repository_owner }}/rekku_the_bot:latest
    - name: Push image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/rekku_the_bot:latest
