name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop", "feat/*", "fix/*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up image tag
      id: vars
      run: echo "tag=rekku_freedom_project:${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.vars.outputs.tag }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Tag image for GHCR
      run: |
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker tag ${{ steps.vars.outputs.tag }} ghcr.io/$REPO_OWNER_LC/rekku_freedom_project:latest

    - name: Push image to GHCR
      run: |
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_OWNER_LC/rekku_freedom_project:latest

    - name: Make image public (one-time per package)
      if: github.event_name == 'push'
      run: |
        echo "🔓 Rendendo il pacchetto pubblico..."
        gh auth login --with-token <<< "${{ secrets.CR_PAT }}"
        REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        gh api --method PATCH /users/${{ github.actor }}/packages/container/rekku_freedom_project \
          -H "Accept: application/vnd.github+json" \
          -f visibility=public || true
      env:
        GH_TOKEN: ${{ secrets.CR_PAT }}
